# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-03 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
